[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /home/objetivosbas/htdocs/sales-target/artisan queue:work database --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
user=objetivosbas
directory=/home/objetivosbas/htdocs/sales-target
numprocs=1
redirect_stderr=true
stdout_logfile=/home/objetivosbas/htdocs/sales-target/storage/logs/worker.log
stopwaitsecs=3600
